pipeline {
    agent { dockerfile true }
    environment {
        AzureACRKey = credentials('AzureACR')
    }
    stages {
        stage('Build Container') {
            steps {
                sh "echo 'poi-container'"
                sh "ls"
                sh "docker info"
            }
        }
    }
}