pipeline {
    agent { dockerfile true }
    environment {
        AzureACRKey = credentials('AzureACR')
    }
    stages {
        stage('Build Container') {
            steps {
                echo "poi-container"
                ls
                docker info
                docker build -t devops/api-poi:${BUILD_NUMBER} apis/poi/web/.
                docker tag devops/api-poi:${BUILD_NUMBER} openhackgpj2acr.azurecr.io/devopsoh/api-poi:latest
                docker tag devops/api-poi:${BUILD_NUMBER} openhackgpj2acr.azurecr.io/devopsoh/api-poi:${BUILD_NUMBER}
                docker login openhackgpj2acr.azurecr.io -u @AzureACRKey_USR -p $AzureACRKey_PSW
                docker push openhackgpj2acr.azurecr.io/devopsoh/api-poi:${BUILD_NUMBER}
            }
        }
    }
}